### ISSUE TITLE
Incorrect port number referrenced repeatedly (2419 instead of 2914)

### ISSUE THREAD

**Issue by duckinator** [smcameron/space-nerds-in-space#289]
In various places, the documentation mentions port 2419 as the gamelobby port, but the [actual port according to IANA](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=54) is 2914.

Notably, 2914 is the default port used by `ssgl_server`, even though the port is listed as 2419 in:

- [`doc/hacking-space-nerds-in-space.html`](https://github.com/smcameron/space-nerds-in-space/blob/master/doc/hacking-space-nerds-in-space.html)
- [`doc/running-in-the-cloud.txt`](https://github.com/smcameron/space-nerds-in-space/blob/master/doc/running-in-the-cloud.txt)
- [a comment in `snis_client.c`](https://github.com/smcameron/space-nerds-in-space/blob/master/snis_client.c#L19977)
- [the output of `snis_launcher`](https://github.com/smcameron/space-nerds-in-space/blob/master/snis_launcher#L84)
- [`ssgl/ssgl_server.6`](https://github.com/smcameron/space-nerds-in-space/blob/master/ssgl/ssgl_server.6) (repeatedly)

Also: 2419 is sometimes returned by `ssgl_get_gamelobby_port()`: https://github.com/smcameron/space-nerds-in-space/blob/master/ssgl/ssgl_get_gamelobby_port.c

**Comment by smcameron** [comment]
Thanks for reporting this.

**Comment by smcameron** [comment]
Should be fixed by:

* f5e73b909b535fb5e1951857d90f3addf10c9e4d  Fix incorrect port number 2419 that should be 2914

**Comment by duckinator** [comment]
Yup, that should do it! ^^

**Comment by Kasijjuf** [comment]
You missed one. Also documented incorrectly on line 47 of [ssgl/README](https://github.com/smcameron/space-nerds-in-space/blob/master/ssgl/README).

**Comment by smcameron** [comment]
Thanks!  Fixed by:

* 42aa5c8cafa29a1f5bf93ff5fa3992ca86ca10f9  Fix another incorrect port value, 2419 should be 2914
